CREATE TABLE users (
  id       INT(11) PRIMARY KEY AUTO_INCREMENT PRIMARY KEY,
  name     VARCHAR(255) NOT NULL,
  email    VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  UNIQUE INDEX email (email)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1;